name: On-Release Image Build to Supervisely Docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: gha-runner-supervisely-ecosystem

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo ${{ github.event.release.tag_name }}
        run: echo ${{ github.event.release.tag_name }}

      - name: Write Tag to ENV variable
        run: echo "LABEL_VERSION=$(echo '${{ github.event.release.tag_name }}' | sed 's/^v//')" >> $GITHUB_ENV

      - name: Build Docker Image geometry-validator:${{ env.LABEL_VERSION }} and push to docker.io
        run: |
          buildctl build \
            --frontend dockerfile.v0 \
            --local context=./ \
            --local dockerfile=./ \
            --output type=image,name=docker.io/supervisely/geometry-validator:${{ env.LABEL_VERSION }},push=true  \
            --export-cache type=registry,ref=docker.io/supervisely/geometry-validator:buildcache,mode=max \
            --import-cache type=registry,ref=docker.io/supervisely/geometry-validator:buildcache

      - name: Build Docker Image geometry-validator:${{ env.LABEL_VERSION }} and push to Internal registry
        run: |
          buildctl build \
            --frontend dockerfile.v0 \
            --local context=./ \
            --local dockerfile=./ \
            --output type=image,name=cr.internal.supervisely.com/supervisely-internal/ecosystem-apps/geometry-validator:${{ env.LABEL_VERSION }},push=true  \
            --export-cache type=registry,ref=docker.io/supervisely/geometry-validator:buildcache,mode=max \
            --import-cache type=registry,ref=docker.io/supervisely/geometry-validator:buildcache

      - name: Build Docker Image geometry-validator:${{ env.LABEL_VERSION }} and push to Enterprise registry
        run: |
          buildctl build \
            --frontend dockerfile.v0 \
            --local context=./ \
            --local dockerfile=./ \
            --output type=image,name=cr.internal.supervisely.com/supervisely-enterprise/ecosystem-apps/geometry-validator:${{ env.LABEL_VERSION }},push=true  \
            --export-cache type=registry,ref=docker.io/supervisely/geometry-validator:buildcache,mode=max \
            --import-cache type=registry,ref=docker.io/supervisely/geometry-validator:buildcache
